POST http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NDZjMzVhNy1jZTNhLTRhYzgtYTI4Yy04N2Q3M2NjMDA2ODciLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc2NDczNDYxOX0.2tDT64sOhyDF_uB3Fn-jFMw_beupMqSmXPKcgr6CtwM

{
    "title": "Curso de IAsdbersber sdsdz",
    "description": "Programação para leigos"
}

#####

GET http://localhost:3333/courses?orderBy=title&page=3
####

GET http://localhost:3333/courses
###

GET http://localhost:3333/courses?search=pyt
####

GET http://localhost:3333/courses/c8edc085-0735-4a64-9fbe-734fd4ceb058
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NDZjMzVhNy1jZTNhLTRhYzgtYTI4Yy04N2Q3M2NjMDA2ODciLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc2NDczNDQ4N30.wnQzXgv-EJ1dnNDQ-cSSqnsQaE4Vr0AhqCSC92D-NDM

######

PUT http://localhost:3333/courses/98ecb290-2d60-4f17-854c-adae2fbabcf7
Content-Type: application/json

{
    "title": "Curso de NodeJs",
    "description": "Curso completo!"
}

##########

PATCH http://localhost:3333/courses/5586ed3a-ca11-4e9d-af71-c5801cf5ceae
Content-Type: application/json

{
    "title": "Curso de Angularr"
}

###

DELETE http://localhost:3333/courses/00c6eaa0-e035-432c-af1d-cb134e618bc6

######

POST http://localhost:3333/sessions
Content-Type: application/json

{
    "email": "Isabelly1@yahoo.com",
    "password": "214580"
}


