POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de Python",
    "description": "Programação com Jango"
}
#####

GET http://localhost:3333/courses?orderBy=title&page=3
####

GET http://localhost:3333/courses
###

GET http://localhost:3333/courses?search=pyt
####

GET http://localhost:3333/courses/0d2755f1-c1aa-419f-aa78-a563673e7227
######

PUT http://localhost:3333/courses/98ecb290-2d60-4f17-854c-adae2fbabcf7
Content-Type: application/json

{
    "title": "Curso de NodeJs",
    "description": "Curso completo!"
}

##########

PATCH http://localhost:3333/courses/98ecb290-2d60-4f17-854c-adae2fbabcf7
Content-Type: application/json

{
    "title": "Curso de Angular"
}


###

DELETE http://localhost:3333/courses/08e5693b-99f8-4053-a50d-0c9d9293eb0f

######


