POST http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NDZjMzVhNy1jZTNhLTRhYzgtYTI4Yy04N2Q3M2NjMDA2ODciLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc2NTE3MDIxNH0.7gwZsL-y3Kyr7srbeN63t2Z6_2IGD0c3K-Mj7Q9qMlo

{
    "title": "Curso de IAsdbersber sdsd sdsez",
    "description": "Programação para leigos vrvr"

}
    
#####

GET http://localhost:3333/courses?orderBy=title&page=3
####

GET http://localhost:3333/courses
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NDZjMzVhNy1jZTNhLTRhYzgtYTI4Yy04N2Q3M2NjMDA2ODciLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc2NTg0NTQ4NH0.jVGp0LJtEZ-WYK_itrIIulMQQMyqTeZJ7WrJfzLbjrA

###

GET http://localhost:3333/courses?search=pyt
####

GET http://localhost:3333/courses/2cbd1246-e8d5-4dba-b22e-e6078edc0840
Authorization: 

######

PUT http://localhost:3333/courses/134597d8-34aa-4ea8-ba68-a3a2fa25a7ac
Content-Type: application/json
Authorization: 

{
    "title": "Curso de NodeJdsv",
    "description": "Curso completo!"
}

##########

PATCH http://localhost:3333/courses/134597d8-34aa-4ea8-ba68-a3a2fa25a7ac
Content-Type: application/json
Authorization: 

{
    "title": "Curso de Angulssarr"
}

###

DELETE http://localhost:3333/courses/c8edc085-0735-4a64-9fbe-734fd4ceb058
Authorization: 

######

POST http://localhost:3333/sessions
Content-Type: application/json

{
    "email": "Isabelly1@yahoo.com",
    "password": "214580"
}


